name: "Entrega Contínua EC2"

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_ec2:
    # Informamos que queremos utilizar como ambiente a versão mais recente do ubuntu dentro
    # do servidor do github actions:
    runs-on: ubuntu-latest
    environment: prod
    # Passos do meu job:
    steps:
    # A Action abaixo faz um git clone do nosso projeto e acessa a pasta do projeto
    # normalmente chamdo de "workflow":
    - uses: actions/checkout@v5

    # A Action abaixo define a versão do GO que iremos usar, que é a "1.22"
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: go build main.go

    - name: SCP to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SECRET_KEY }}
        source: "templates,assets,main"
        target: /home/${{ secrets.EC2_USERNAME }}

    - name: Restart service
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SECRET_KEY }}
        script: sudo systemctl restart projeto
