name: Integração Contínua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  ci:
    # Informamos que queremos utilizar como ambiente a versão mais recente do ubuntu dentro
    # do servidor do github actions:
    runs-on: ubuntu-latest
    # Passos do meu job:
    steps:
    # A Action abaixo faz um git clone do nosso projeto e acessa a pasta do projeto
    # normalmente chamdo de "workflow":
    - uses: actions/checkout@v5

    # A Action abaixo define a versão do GO que iremos usar, que é a "1.22"
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Inicia banco
      run: docker-compose up -d postgres

    - name: Lint
      run: docker run --rm -itv $(CURDIR):/app -w /app golangci/golangci-lint golangci-lint run controllers/ database/ models/ routes/

    - name: Test
      run: go test -v main_test.go